### ISSUE TITLE
No initialize method for IBClient class after update?

### ISSUE THREAD

**Issue by YuriWerewolf** [lbilli/rib#22]
Looks like there is no initialize function now for the IBClient object now.
ic   <- IBClient$new(wrap)
Error in IBClient$new(wrap) : 
  Called new() with arguments, but there is no initialize method.

I have checked the code in the class description and don't see it as well.

**Comment by lbilli** [comment]
As of 71d7e1b there's no need for an initializer as `wrap` has been moved out of `IBClient`. Instead, it is passed as argument to `checkMsg()`.

The new way is:
```R
ic <- IBClient$new()

ic$checkMsg(wrap)
```

**Comment by YuriWerewolf** [comment]
Thanks, got you
