### ISSUE TITLE
Simple example crashing both rstudio and R client

### ISSUE THREAD

**Issue by grandtiger** [lbilli/rib#3]
Thanks a lot for sharing this package! I am very excited to see it and try it as soon as I got home. Unfortunately, I couldn't get it to work. I am using RStudio 1.2.1335 and R 3.5.3. Every time I tried to run the following simple example, the code before line ```ic$checkMsg(2)``` works, but when running this line, RStudio 1.2.1335 or R 3.5.3 client will crash immediately. I can not see any error message before the crash. How can I trouble shoot this issue? 

```
library(rib)

# Instantiate wrapper, client and connect
wrap <- IBWrapSimple$new()
ic   <- IBClient$new(wrap)
ic$connect(port=4002, clientId=1)

# Send requests, e.g.:
contract <- IBContract("GOOG")
ic$reqContractDetails(11, contract)

# more requests can go here...

# Parse responses.
# Might need to be called several times to process all messages
ic$checkMsg(2)

# Find results in
wrap$context

# Disconnect
ic$disconnect()
```

**Comment by lbilli** [comment]
Hi, thanks for trying it out.
Few questions:
- which OS?
- could you try this in a plain R session (not inside  RStudio), with TWS listening on port `4002`?
```R
library(rib)
wrap <- IBWrapSimple$new()
ic   <- IBClient$new(wrap)
ic$connect(port=4002, clientId=1)
ic$checkMsg()
```

**Comment by grandtiger** [comment]
@lbilli sorry, I forgot to follow up until seeing your message about new release today. I just tried the latest version, it's not crashing rstudio on windows 10 any more. However, the last line generated error message below.
```
> library(rib)
> wrap <- IBWrapSimple$new()
> ic   <- IBClient$new(wrap)
> ic$connect(port=7497, clientId=1)
Server Version and Timestamp: 151 20190617 22:50:32 EST 
> ic$checkMsg()
Error in readBin(private$socket, raw(), n = len) : invalid 'n' argument
```
